#!/bin/dash
config=~/.dashboard
case "$1" in
        start)
		if [ ! -f "$config" ]
		then
		exit
		else
		echo "Launching"
		fi
		tmux resize-pane -y $(echo $(tmux display -p '#{window_height}') - $(echo \($(tmux display-message -p "#{pane_index}") +2\) \* 3 | bc) | bc)
                panes=$(tmux display-message -p "#{pane_index}")
		paneCount=$(echo "$(wc -l $config| cut -f1 -d\ )+1"|bc)
                while [ $panes -lt $paneCount ]
                do
		tmux split-window #-t $(tmux display-message -p '#I')
		tmux select-layout even-vertical
                panes=$(echo $panes+1|bc)
                done
		tmux resize-pane -y 3 -t 0
		tmux swap-pane -U
		tmux send-keys -t 0 "htop -d 5" ENTER
		panes=1
		for i in $(cat ~/.dashboard)
		do
		tmux resize-pane -y 2 -t $(tmux display-message -p '#I').$panes
		tmux send-keys -t $(tmux display-message -p '#I').$panes "while :; do ssh $i -t htop -d 5; done" ENTER
		panes=$(echo $panes+1|bc)
		done
		tmux select-pane -t $panes
		;;
	kill)
                panes=$(tmux display-message -p "#{pane_index}")
                while [ $panes -gt 0 ]
                do
                tmux kill-pane -t $(echo $panes-1|bc)
                panes=$(echo $panes-1|bc)
                done
		;;
	fix)
		paneCount=$(wc -l $config| cut -f1 -d\ )
		panes=0
		while [ $panes -le $paneCount ]
                do
                tmux resize-pane -y2 -t $panes
                panes=$(echo $panes+1|bc)
		done
		;;
	restart)
		dashboard kill
		dashboard start
		;;
	help)
		echo "help (this message)"
		echo "start (creates the tmux-panes and ssh->htop)"
		echo "kill (Make it go away)"
		echo "restart (dashboard kill && dashboard start)"
		echo "push-htop-config (makes setup easy of htop on each node)"
		;;
	push-htop-config)
		echo "This will replace the htop config on all nodes."
		echo "Do you wish to continue? (y/n)"
		read answer
		if [[$answer=y*]] 
			then for i in $(cat $config)
				do ssh $i -t "mv ~/.config/htop/htoprc ~/.config/htop/htoprc.bak && echo 'fields=0 48 17 18 38 39 40 2 46 47 49 1
sort_key=46
sort_direction=1
hide_threads=0
hide_kernel_threads=1
hide_userland_threads=0
shadow_other_users=0
show_thread_names=0
show_program_path=1
highlight_base_name=0
highlight_megabytes=1
highlight_threads=1
tree_view=0
header_margin=0
detailed_cpu_time=0
cpu_count_from_zero=0
update_process_names=0
account_guest_in_cpu_meter=0
color_scheme=0
delay=15
left_meters=CPU Memory
left_meter_modes=1 1
right_meters=Uptime Hostname
right_meter_modes=2 2' > ~/.config/htop/htoprc"
			done
		fi
		;;
esac
		echo "huh... this program doesn't know that argument, maybe try one from below..."
		echo
                echo "help (this message)"
                echo "start (creates the tmux-panes and ssh->htop)"
                echo "kill (Make it go away)"
                echo "restart (dashboard kill && dashboard start)"
                echo "push-htop-config (makes setup easy of htop on each node)"

exit 0
